version: '3.9'

services:
  fc.codeflix.catalog.db:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

networks:
  default:
    name: service_catalog